### ISSUE TITLE
请问这个图是用什么软件做的

### ISSUE THREAD

**Issue by bopo** [SangKa/react-roadmap#1]
请问这个图是用什么软件做的

**Comment by SangKa** [comment]
README 上有写:

> 学习路线图是使用 Draw.io 画的。文件就放在 /src 目录下。想要修改思维导图，先打开 draw.io ，点击 Open Existing Diagram 然后选择 xml 文件。之后就会打开思维导图，修改之后上传后更新 README 的 PNG 图片 (需要导出)，然后提交 PR
